# Generated by Django 5.0.4 on 2024-04-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trainedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainedModel',
        ),
    ]
